export const books = [
    {
     id: 1,
     title: "A Game Of Thrones",
     author: "George R. R. Martin",
     img: "/book1.jpeg",
     category: "Fantasy",
     language: "English",
     year: "1996",
     description: "A Game of Thrones takes place over one year on or near the fictional continent of Westeros. The story begins when King Robert visits the northern castle Winterfell to ask Ned Stark to be his right-hand assistant, or Hand of the King.",
    },
    {
     id: 2,
     title: "The Colour Of Magic",
     author: "Terry Pratchett",
     img: "/book2.jpeg",
     category: "Fantasy",
     language: "English",
     year: "1983",
     description: "A humorous fantasy novel about the adventures of an inept wizard named Rincewind in the strange and magical world of Discworld.",
    },
    {
     id: 3,
     title: "The Lord of the Rings",
     author: "J. R. R. Tolkien",
     img: "/book3.jpeg",
     category: "Fantasy",
     language: "English",
     year: "1954",
     description: "An epic high-fantasy novel about a quest to destroy the One Ring and defeat the Dark Lord Sauron.",
    },
    {
     id: 4,
     title: "Jonathan Strange & Mr Norrell",
     author: "Susanna Clarke",
     img: "/book4.jpeg",
     category: "Fantasy",
     language: "English",
     year: "2004",
     description: "A historical fantasy novel set in 19th-century England, where magic returns after centuries of absence.",
    },
    {
     id: 5,
     title: "The Name of the Wind",
     author: "Patrick Rothfuss",
     img: "/book5.jpeg",
     category: "Fantasy",
     language: "English",
     year: "2007",
     description: "The story of Kvothe, an orphaned and prodigiously gifted boy who becomes a legendary figure.",
    },
    {
     id: 6,
     title: "Carrion Comfort",
     author: "Dan Simmons",
     img: "/book6.jpg",
     category: "Horror",
     language: "English",
     year: "1989",
     description: "A novel portraying a tiny fraction of humanity that has immense psychic powers, which they refer to as The Ability.",
    },
    {
     id: 7,
     title: "The Terror",
     author: "Dan Simmons",
     img: "/book7.jpg",
     category: "Horror",
     language: "English",
     year: "2007",
     description: "A historical horror novel about the ill-fated Franklin expedition and their encounter with a mysterious creature in the Arctic.",
    },
    {
     id: 8,
     title: "Dracula",
     author: "Bram Stoker",
     img: "/book8.jpg",
     category: "Horror",
     language: "English",
     year: "1897",
     description: "An 1897 Gothic horror novel by Irish author Bram Stoker.",
    },
    {
     id: 9,
     title: "Ghost Story",
     author: "Peter Straub",
     img: "/book9.jpeg",
     category: "Horror",
     language: "English",
     year: "1979",
     description: "A horror novel about a group of old men haunted by a dark secret from their past.",
    },
    {
     id: 10,
     title: "The Strangler",
     author: "William Landay",
     img: "/book10.jpeg",
     category: "Horror",
     language: "English",
     year: "2007",
     description: "A legal thriller about a series of murders and the lawyer defending the accused.",
    },
    {
     id: 11,
     title: "All the Devils Are Here",
     author: "Louise Penny",
     img: "/book11.jpeg",
     category: "Mystery",
     language: "English",
     year: "2020",
     description: "The Hidden History of the Financial Crisis.",
    },
    {
     id: 12,
     title: "The Beast Must Die",
     author: "Cecil Day-Lewis",
     img: "/book12.jpg",
     category: "Mystery",
     language: "English",
     year: "1938",
     description: "A detective novel about a man who vows revenge on the hit-and-run driver who killed his son.",
    },
    {
     id: 13,
     title: "Kitty Peck and the Music Hall Murders",
     author: "Kate Griffin",
     img: "/book13.jpeg",
     category: "Mystery",
     language: "English",
     year: "2013",
     description: "A mystery novel set in Victorian London's music hall scene, featuring a young woman investigating a series of murders.",
    },
    {
     id: 14,
     title: "Sandrine's Case",
     author: "Thomas H. Cook",
     img: "/book14.jpg",
     category: "Mystery",
     language: "English",
     year: "2018",
     description: "A mystery novel about a detective investigating a cold case involving a missing woman.",
    },
    {
     id: 15,
     title: "Sandrine's Case",
     author: "Thomas H. Cook",
     img: "/book14.jpg",
     category: "Mystery",
     language: "English",
     year: "2018",
     description: "A mystery novel about a detective investigating a cold case involving a missing woman.",
    },
    {
     id: 16,
     title: "The House in the Pines",
     author: "Ana Reyes",
     img: "/book16.jpeg",
     category: "Thriller",
     language: "English",
     year: "2023",
     description: "A thriller about a woman haunted by a past trauma who becomes entangled in a dangerous mystery.",
    },
    {
     id: 17,
     title: "The Martian",
     author: "Andy Weir",
     img: "/book17.jpeg",
     category: "Thriller",
     language: "English",
     year: "2011",
     description: "A science fiction novel about an astronaut who is stranded on Mars and must use his ingenuity to survive.",
    },
    {
     id: 18,
     title: "Monkey Beach",
     author: "Eden Robinson",
     img: "/book18.jpeg",
     category: "Thriller",
     language: "English",
     year: "2000",
     description: "A thriller about a young woman's search for her missing brother, interwoven with indigenous mythology and supernatural elements.",
    },
    {
     id: 19,
     title: "The Talented Mr Ripley",
     author: "Patricia Highsmith",
     img: "/book19.jpeg",
     category: "Thriller",
     language: "English",
     year: "1955",
     description: "A psychological thriller about a con artist who becomes obsessed with a wealthy young man and assumes his identity.",
    },
    {
     id: 20,
     title: "The Secret History",
     author: "Donna Tartt",
     img: "/book20.jpeg",
     category: "Thriller",
     language: "English",
     year: "1992",
     description: "A mystery and psychological thriller about a group of classics students who become involved in a murder.",
    },
    {
     id: 21,
     title: "The Hitchhiker's Guide to the Galaxy",
     author: "Douglas Adams",
     img: "/book21.jpeg",
     category: "Science Fiction",
     language: "English",
     year: "1979",
     description: "A comedic science fiction series about the adventures of the last surviving man after Earth is destroyed.",
    },
    {
     id: 22,
     title: "American War",
     author: "Omar El Akkad",
     img: "/book22.jpeg",
     category: "Science Fiction",
     language: "English",
     year: "2017",
     description: "A second American Civil War, a devastating plague, and one family caught deep in the middle.",
    },
    {
     id: 23,
     title: "Feed",
     author: "M. T. Anderson",
     img: "/book23.jpg",
     category: "Science Fiction",
     language: "English",
     year: "2002",
     description: "A cyberpunk, satirical, dystopian, young-adult novel by M. T. Anderson.",
    },
    {
     id: 24,
     title: "The Foundation Trilogy",
     author: "Isaac Asimov",
     img: "/book24.jpg",
     category: "Science Fiction",
     language: "English",
     year: "1951",
     description: "It is the story of the Galactic Empire, crumbling after twelve thousand years of rule.",
    },
    {
     id: 25,
     title: "The Handmaid's Tale",
     author: "Margaret Atwood",
     img: "/book25.jpeg",
     category: "Science Fiction",
     language: "English",
     year: "1985",
     description: "A dystopian novel set in a totalitarian society where women are subjugated and used for reproductive purposes.",
    },
   ];